default_context:
  project_name: 'rail_license_generator_backend'
  project_slug: 'rail_license_generator_backend'
  domain_main: 'rail_license_generator_backend.com'
  domain_staging: 'stag.rail_license_generator_backend.com'
  docker_swarm_stack_name_main: 'rail_license_generator_backend-com'
  docker_swarm_stack_name_staging: 'stag-rail_license_generator_backend-com'
  secret_key: '0250cfd981975235c7640233439549828f8af588ba3bf780e060870de9786c1c'
  first_superuser: 'admin@rail_license_generator_backend.com'
  first_superuser_password: 'meat-have-fraction-FIELD'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.rail_license_generator_backend.com", "https://stag.rail_license_generator_backend.com", "https://rail_license_generator_backend.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@rail_license_generator_backend.com'
  postgres_password: '1d746d885b6ffce99a338efb5c0edd00f6aa865d61baf913d47c49f90943e98b'
  pgadmin_default_user: 'admin@rail_license_generator_backend.com'
  pgadmin_default_user_password: 'meat-have-fraction-FIELD'
  traefik_constraint_tag: 'rail_license_generator_backend.com'
  traefik_constraint_tag_staging: 'stag.rail_license_generator_backend.com'
  traefik_public_constraint_tag: 'traefik-public'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
