"""Add additional project information

Revision ID: 4f6d57b75281
Revises: fd721bd9c282
Create Date: 2024-08-24 11:53:53.527125

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4f6d57b75281'
down_revision = 'fd721bd9c282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('license', sa.Column('project_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('license', sa.Column('additional_information', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('license', 'additional_information')
    op.drop_column('license', 'project_url')
    # ### end Alembic commands ###
